// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCezNZo6tgKyWz-G1ayTYWa3Ea1VH9tB1w',
    appId: '1:1047357628765:web:48e64c4ad7c18b531188b4',
    messagingSenderId: '1047357628765',
    projectId: 'ditonton-6592f',
    authDomain: 'ditonton-6592f.firebaseapp.com',
    storageBucket: 'ditonton-6592f.appspot.com',
    measurementId: 'G-KV41G1XGDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDDlpkv2QuAlGTVT6dXFvmIHcPtIhrNqk',
    appId: '1:1047357628765:android:5a512a78e87475ad1188b4',
    messagingSenderId: '1047357628765',
    projectId: 'ditonton-6592f',
    storageBucket: 'ditonton-6592f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDff2H5ckHXRTh_FFKBg0Xt7ZuFrauWirg',
    appId: '1:1047357628765:ios:18094ee5a32762191188b4',
    messagingSenderId: '1047357628765',
    projectId: 'ditonton-6592f',
    storageBucket: 'ditonton-6592f.appspot.com',
    iosClientId: '1047357628765-gaqs48snm6kf85tdlchl5tlhbfr8pa61.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
